// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// internalAdministratorDao is internal type for wrapping internal DAO implements.
type internalAdministratorDao = *internal.AdministratorDao

// administratorDao is the data access object for table administrator.
// You can define custom methods on it to extend its functionality as you wish.
type administratorDao struct {
	internalAdministratorDao
}

var (
	// Administrator is globally public accessible object for table administrator operations.
	Administrator = administratorDao{
		internal.NewAdministratorDao(),
	}
)

// Fill with you ideas below.
