// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// internalInOutDao is internal type for wrapping internal DAO implements.
type internalInOutDao = *internal.InOutDao

// inOutDao is the data access object for table in_out.
// You can define custom methods on it to extend its functionality as you wish.
type inOutDao struct {
	internalInOutDao
}

var (
	// InOut is globally public accessible object for table in_out operations.
	InOut = inOutDao{
		internal.NewInOutDao(),
	}
)

// Fill with you ideas below.
