// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// internalStaffDao is internal type for wrapping internal DAO implements.
type internalStaffDao = *internal.StaffDao

// staffDao is the data access object for table staff.
// You can define custom methods on it to extend its functionality as you wish.
type staffDao struct {
	internalStaffDao
}

var (
	// Staff is globally public accessible object for table staff operations.
	Staff = staffDao{
		internal.NewStaffDao(),
	}
)

// Fill with you ideas below.
