// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// internalStudentDao is internal type for wrapping internal DAO implements.
type internalStudentDao = *internal.StudentDao

// studentDao is the data access object for table student.
// You can define custom methods on it to extend its functionality as you wish.
type studentDao struct {
	internalStudentDao
}

var (
	// Student is globally public accessible object for table student operations.
	Student = studentDao{
		internal.NewStudentDao(),
	}
)

// Fill with you ideas below.
